name: maka_admin
description: 玛卡之声社区 管理面板
publish_to: 'none'
version: 0.2.1+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.0.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#EF4444"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
